Ambassador_wahl1-post
unitaryfund/unitary-fund pull request #156
Opened 2021-11-08 23:39 UTC by crazy4pi314

@misty-w I think this is ready to go! Have a look and see if it matches what  you drafted before

2021-11-09 00:52 UTC, Misty-W commented
LGTM @crazy4pi314, looking forward to seeing it on the website!

2021-11-09 10:10 UTC, nathanshammah approved these changes
I reviewed the markdown and it reads very well, well done @Misty-W!

I did not check that the image links are working.

The file name looks a bit strange. I imagine the "1" is to order w.r.t. other ambassador stories. I propose to change it to "ambassador_1_wahl" and keep that convention, so that they are also ordered when listed in a folder.

2021-11-09 10:15 UTC, nathanshammah requested changes
I made some changes based on the formatting in [the Krylov blogpost](https://github.com/unitaryfund/unitary-fund/blob/4de949b7b341b1bfa9e621807c2db4d4ef67b6c8/posts/_markdown/krylov.md), where from the markdown file the figures show up. So I proposed these changes to mimic that. 

I would also change the title of the files (previous comment).

2021-11-09 10:15 UTC, nathanshammah commented on posts/_markdown/ambassador_wahl1.md
> +![Github issue from unitaryHACK](..\images\ambassador_wahl1_card.png "Github issue from unitaryHACK")
```suggestion
![Github issue from unitaryHACK](../images/ambassador_wahl1_card.png "Github issue from unitaryHACK")
```

2021-11-09 10:15 UTC, nathanshammah commented on posts/_markdown/ambassador_wahl1.md
> +![Energy landscape plot from “ZNE with pyQuil and parametric compilation” tutorial](..\images\ambassador_wahl1_pyquil.png "Energy landscape plot from “ZNE with pyQuil and parametric compilation” tuto
```suggestion
![Energy landscape plot from “ZNE with pyQuil and parametric compilation” tutorial](../images/ambassador_wahl1_pyquil.png "Energy landscape plot from “ZNE with pyQuil and parametric compilation” tutorial")
```

2021-11-09 10:15 UTC, nathanshammah commented on posts/_markdown/ambassador_wahl1.md
> +![Energy landscape plot from “Variational Quantum Eigensolver improved with Zero Noise Extrapolation” tutorial](..\images\ambassador_wahl1_landscape.png "Energy landscape plot from “Variational Quant
```suggestion
![Energy landscape plot from “Variational Quantum Eigensolver improved with Zero Noise Extrapolation” tutorial](../images/ambassador_wahl1_landscape.png "Energy landscape plot from “Variational Quantum Eigensolver improved with Zero Noise Extrapolation” tutorial")
```

2021-11-10 16:16 UTC, nathanshammah commented
Looking at #155, there the path there is `.../.../images`, not just `../images`. The first path is correct to visualize the images from a md file since there is a  `posts/_markdown` folder, which is one level lower than the one for html files, `posts`. Looking at [VQA post raw file](https://raw.githubusercontent.com/unitaryfund/unitary-fund/master/posts/_markdown/mitiq_vqa_performance.md), it looks like the correct one is `../` only. It may be nice to visualize both posts (also in markdown), either by placing at the same level from the image folder, or specifying this in someway that works for both.

2021-11-10 17:15 UTC, crazy4pi314 commented
> I reviewed the markdown and it reads very well, well done @Misty-W!
> 
> I did not check that the image links are working.
> 
> The file name looks a bit strange. I imagine the "1" is to order w.r.t. other ambassador stories. I propose to change it to "ambassador_1_wahl" and keep that convention, so that they are also ordered when listed in a folder.

The number here was because some ambassadors may write more than one post. I will change the number to intro, to avoid confusion.

2021-11-10 17:28 UTC, crazy4pi314 commented
Ok, I have fixed all the path issues, the one thing I noticed was that it's missing some links for where folks can find you @Misty-W! If you want to comment or PR what links/email/handles you want (no obligation to any in particular) then I can get this merged!

2021-11-10 18:11 UTC, Misty-W commented
Twitter: @mistyawahl
Github: https://github.com/Misty-W
LinkedIn: https://www.linkedin.com/in/misty-wahl

2021-11-10 18:37 UTC, crazy4pi314 commented
> @crazy4pi314, that reminds me, I also submitted a bio awhile back, will that be published as well?
 Yup, I am working on getting a people page with ambassadors on the website :)

2021-11-10 18:39 UTC, merged