UnitaryHACK 2022 wrapup blog post
unitaryfund/unitary-fund pull request #237
Opened 2022-07-07 18:26 UTC by nathanshammah

2022-07-07 21:21 UTC, Misty-W requested changes

2022-07-07 21:21 UTC, Misty-W commented on posts/_markdown/2022_unitaryhack_wrapup.md
> +For **Alberto Maldonado**, maintainer from the Quantum Universal
```suggestion
 
 Hear what our community members had to say about unitaryHACK!
 
 From **Alberto Maldonado**, maintainer from the Quantum Universal
```

2022-07-08 14:06 UTC, willzeng commented
Looks good to me after changes suggested by @Misty-W

2022-07-08 14:34 UTC, merged

2022-07-08 14:37 UTC, nathanshammah commented
Thanks @Misty-W!