Add blog posts for HODL
unitaryfund/unitary-fund pull request #241
Opened 2022-07-15 14:47 UTC by at2005

2022-07-26 10:05 UTC, willzeng commented
Hi @at2005 Thanks for posting! Is this ready for review?

2022-07-28 10:50 UTC, nathanshammah requested changes
Thanks @at2005! Excellent job. Some minor technicalities:
- Can you please generate the html page, using the pandoc commands reported in the [readme](https://github.com/unitaryfund/unitary-fund#writing-a-blog-post).
Please add a link to the html page to the blog index, blog.html?
- Also, please have a double check at the html file locally to check that pandoc converted it correctly, e.g., https://github.com/unitaryfund/unitary-fund/issues/243.
- What md file needs to be included, there are two now
- there is an image at the top that I think is not supposed to be there?
- I'm not familiar with the way images are included: can they included in the website for more reliability in the future.

2022-08-07 22:28 UTC, at2005 commented
Hi, I've updated the files accordingly :) There is now one HTML file (hodl.html), and have edited it to format it properly and added the link to blog.html.

2022-08-19 15:11 UTC, nathanshammah approved these changes

2022-08-19 15:11 UTC, nathanshammah commented on posts/_markdown/qiskit_hodl.md
> +Jun 28
```suggestion
2022-08-19
```

2022-08-19 15:11 UTC, nathanshammah commented on posts/hodl.html
> +                                <p>Jun 28</p>
```suggestion
                                <p>2022-08-19</p>
```

2022-08-19 15:11 UTC, nathanshammah commented on blog.html
> +                    <span class="blog-post-date">7 August, 2022</span>
```suggestion
                    <span class="blog-post-date">19 August, 2022</span>
```

2022-08-19 15:12 UTC, merged