Add grant winner series blog post, from Alowina
unitaryfund/unitary-fund pull request #252
Opened 2022-08-17 15:59 UTC by WrathfulSpatula

2022-08-18 14:11 UTC, nathanshammah requested changes
Thanks @WrathfulSpatula.
- Can you please include the md file? It is easier to review and it's good that we keep a copy in the markdown folder too, as in the future we may use that as a main reference in a new website build. I'll review the md file then. 
- Please make the title more explicit, like other ones: Even something like "Inaugurating the Grant Winner Video Series"
- @Misty-W please review and edit the blog post: It should include your perspective!

2022-08-18 14:58 UTC, natestemen commented
> Can you please include the md file? It is easier to review and it's good that we keep a copy in the markdown folder too, as in the future we may use that as a main reference in a new website build.

Just FYI [this PR](https://github.com/unitaryfund/unitary-fund/pull/242) did not have an associated markdown file either. Not sure we'd really want to go back and change it, but thought I'd surface it in case this is a problem.

2022-08-23 16:02 UTC, natestemen submitted a review, later dismissed
LGTM! 🚢

2022-08-23 16:12 UTC, nathanshammah commented
@natestemen no need to do extra work now, but whenever possible, when we catch it, I'd aim to include the .md file for consistency. It also simplifies review of the text (which I haven't done yet) as it does not force one to fork this and host it locally. It takes one line with `pandoc` to generate it. 

For @Misty-W, integrating my previous comments above:

- Please include the youtube-nocookie link as embedded video, e.g. as done for the [Metriq blog](https://unitary.fund/posts/metriq_release.html) post, so that the video window previews in the page. 

- Update date in the blog index and post page (it may be needed to rebase it to include the recent additions from the UF interns).

2022-08-25 22:27 UTC, Misty-W requested changes

2022-08-25 22:27 UTC, Misty-W commented on posts/grant_winner_series.html
> +                                <p>We are very excited to share our first video for Unitary Fund’s Grant Winner series! The series will feature some of our grant winners, their projects, their experi
```suggestion
                                <p>We are very excited to share our first episodes of Unitary Fund’s Grant Winner video series! Watch to learn more about our featured grant winners, their projects, their experience after winning the grant, and what they’re working on now.</p>
```

2022-08-25 22:27 UTC, Misty-W commented on posts/grant_winner_series.html
> +                                <p>Hosted by our very own, Misty Wahl– our first video features Pedro Rivero, author of QRAND and our second video is with Lia Yeh, Samanvay Sharma, and Alberto Maldon
```suggestion
                                <p>Hosted by UF Technical Staff Member Misty Wahl– our first video features Pedro Rivero, author of QRAND and our second video is with Lia Yeh, Samanvay Sharma, and Alberto Maldonado with PIQUE.</p>
```

2022-08-25 23:48 UTC, Misty-W requested changes

2022-08-25 23:48 UTC, Misty-W commented on posts/_markdown/grant_winner_series.md
> +date: 18 February 2022
```suggestion
date: 26 August 2022
```

2022-08-26 00:20 UTC, Misty-W requested changes

2022-08-26 00:20 UTC, Misty-W commented on posts/grant_winner_series.html
> +                                <p><a href="https://youtu.be/LSOCHWSPvUc">About QRAND</a>: QRAND introduces a versatile interface layer between NumPy and several quantum computing platforms (qiskit,
```suggestion
              <iframe
                width="560"
                height="315"
                src="https://www.youtube-nocookie.com/embed/LSOCHWSPvUc""
                title="YouTube video player"
                style="border: none"
                allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                allowfullscreen
              ></iframe>
              <p>About QRAND</a>: QRAND introduces a versatile interface layer between NumPy and several quantum computing platforms (qiskit, cirq, qsharp...), along with some useful functionality that enables the production of quantum random numbers (QRN) according to different quantum protocols, and for a wide variety of probability distributions.</p>
```

2022-08-26 01:25 UTC, Misty-W approved these changes

2022-08-26 18:17 UTC, nathanshammah approved these changes
LGMT, thanks Misty!

2022-08-26 18:17 UTC, merged